include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_lambdas: true
    use_super_parameters: true
    sort_child_properties_last: true
